language: groovy
jdk:
- openjdk8
dist: xenial
sudo: false
branches:
  only:
  - master
  - develop
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: NftHiDl5EWWv/sgHAYULOe/9wfLFgzkWrnczNhoFxBhMbef3townuHJtQmuqoQ+l6UDLynaGmcSSDuvC9Pp14zOUBxDvF0b+8irKWtqp9MglBO7HAUrllAEHeipU2OT69lrBq4yznfsczEJBNO5pWqR8TrTbs57E2RzH46/b1BCnqVSA0OJwoiVDj4iUX0FK++3E26Kl56fg+xD1iWANqjrM6eTXeghmUcw5IBrnnxYhUwgr+0qwfoOe8iWXis9O0FN+y0PIc4SXqjOMJ0xOOcElRq6kz1XglyS0Idj0j00Bpf7cyv1MQ7Go281MxN5DG/urJu017FOYqy4jUWiRC2vIXSOgxSG6bONnQsIZpxGU+5xTIuz2BGTRWQMzkY+vDEP2grDmTyyquXQBHJbjfpplF8erdI0XaZs33fAyeWmKqxJWk6isAAezPPlTmJaSuKdF2jd0pUs01biEjHrduTWuZ6yQ/porG92Khi8ujn7FPovoX+kF6vU41uZButTsc7eSfyYUVv5Bg/7TVLuDu+xNNhXIrfxLPj+KJwIok0m052WRfSUsS7XaSZ90PzTP+iabsEdV+zHOpJSNMXgVw5M+gTqZhHtAphmbfaiQpN4AkRUD4+Mk7g1jlmmq4UDbq1a3kJb25tF7mkzscDa/vXYrC3GPU5EU+OLE63D4SF4=
  - secure: nRQEXxe84ir0hWae7JjD/wYrwcfGr1kQBfs6deCj1+hajmXYMr25ejcKxJ7XivI4gj+rR4lubuWLh+10fB/9ItIWIf+6QaUm0WN5mdVeUQu1+0eW+E5IjWrFH8kmU+4fUFxarI7yvyVODVUWy3ttTa2nNvMG7CLIOQ43jZB1z8DdAgkxnovPW14d9kB1AGWhoOkMeTqPInElvm61mK1FMefAbIrDChOO3XsuBk2hNTeIRJ9GFUjGLzIxLbmci+xn19pXlCj9PEHtb862sY3EY0v0V2HsUQJxAkIDlDLIHYHG7IsSQb5gnf+nN2K88FtZ7A/wFzBbPLYcgUO2eTjd9RCDXMhnpNTvL5xnkZxTQuTiPsKP145wqRrELjmsIMiAjybV1IkASie7QLvO2WUEoyNvM1+8edFlHxL54fESRyA8z5hS7QlL+3GMaTAbNIpszyo7fqceJ5+Egz3PYq3xsod6jbM0FmBi6voi0UB/yQEp5u6j6mG2e61nrGM3wOYADfo1p+9BM5/RfsNGHtJ/ODW9VffDE+/pZCECnLuUqEJVVuqdXm49fbPQWuIXBxlx871WGSsuytbel0hPwCeVL0WOqD4y41sj3xjpY1dIINjBoUgIlLTH7aMI+IxrjFUbojoD4xMhhu1ouS4+70RLcuHcICPmUePkTqBKVA62RG0=
