---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: uk.org.nbn.places.plugin
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
    
---
hibernate:
    show_sql: false
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: true
        region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: "root"
    password:
     properties:
        # http://www.grails.org/doc/latest/guide/single.html#dataSource
        # see http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes for more
        timeBetweenEvictionRunsMillis: 60000 # milliseconds (default: 5000)
        testOnBorrow: true # default: false
        testOnReturn: false # default: false
        testWhileIdle: true # default: false
        validationQuery: "SELECT 1" # default: null
        validationQueryTimeout: 10 # seconds (default: -1 i.e. disabled)
        validationInterval: 30000 # milliseconds, default is 30000 (30 seconds)
        removeAbandoned: true # # default: false
        removeAbandonedTimeout: 300 # seconds (default: 60)
        logAbandoned: true # adds some overhead to every borrow from the pool, disable if it becomes a performance issue
        logValidationErrors: true # default: false, logs validation errors at SEVERE
        # NOTE: removeAbandoned: true OR testWhileIdle: true enables the Pool Cleaner. There is a bug with the
        # pool cleaner which causes deadlocks when using older mysql jdbc drivers. This configuration has been
        # tested successfully with mysql:mysql-connector-java:5.1.34.
        # mysql jdbc connection properties - see http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
        dbProperties:
            autoReconnect: true
            connectTimeout: 0
            useUnicode: true
            characterEncoding: "UTF-8"

environments:
    development:
        dataSource:
            # dbCreate: "update"
            url: "jdbc:mysql://localhost:3306/nbn_places?autoReconnect=true&useSSL=false"
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: "root"
            password: "password"

        hibernate:
            show_sql: true
            cache:
                queries: false
                use_second_level_cache: false
                use_query_cache: false
        grails:    
            gorm:       
                failOnError: true
    test:
        dataSource:
            dbCreate: "create-drop"
            pooled: true
            driverClassName: org.h2.Driver
            url: "jdbc:h2:mem:default"
            username: "sa"
            password: ""
        grails:    
            gorm:       
                failOnError: true
    production:
        dataSource:
            